### ISSUE TITLE
GetCookie у Handler

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_SIBIRSKAYA_KORONA#4]
https://github.com/go-park-mail-ru/2020_1_SIBIRSKAYA_KORONA/blob/1bbda97ed2b148c3fd66d5ab884e7665a3f1cd82/main.go#L185-L193

- Не говорящее название функции, вы ведь получаете не куку, а имя пользователя из куки. Так и назоваите функцию `getNameFromCookie`. 
- в 189-ей строчку явная проверка `err != nil`, но при этом функция не возвращает ошибку. Если функция может породить ошибку, то [принято](https://blog.golang.org/error-handling-and-go) ее возвращать. Это упрощает отладку и прозрачность работы функций.
- Если переменную можно не объявлять, то объявлять переменную не нужно

```
func (this *Handler) getNameFromCookie(r *http.Request) (string, error) { 
 	session, err := r.Cookie("session_id") 
 	if err != nil { 
 		return "", err
 	} 
        // session можно не проверять на "", потому что GetSession() вернет false, что породит ошибку `Не найдено`
        name, isFound := this.sessionStore.GetSession(session.Value) 
        if !isFound {
              return "", errors.New("Не найдено")
        }
 	return name, nil
 } 
```

**Comment by chtvrv** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Тесты](https://trello.com/c/zEwLBVcx/5-%D1%82%D0%B5%D1%81%D1%82%D1%8B)
